apiVersion: v1
kind: Service
metadata:
  name: shortener-frontend
spec:
  selector:
    app: shortener-frontend
  ports:
    - port: 80
      targetPort: 5173
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-frontend
  template:
    metadata:
      labels:
        app: shortener-frontend
    spec:
      containers:
        - name: shortener-frontend
          image: lekanbabawale/shortener-frontend:1.0
          ports:
            - containerPort: 5173
          env:
            - name: VITE_BACKEND_HOST
              value: http://192.168.49.2
            - name: VITE_BACKEND_PORT
              value: "31198"
          imagePullPolicy: Always
